// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/PakornPK/rent-building/internal/entities"
	"github.com/PakornPK/rent-building/internal/repositories"
	"sync"
)

// Ensure, that UserRepositoryMock does implement repositories.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ repositories.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of repositories.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CreateFunc: func(user ...entities.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id int) error {
//				panic("mock out the Delete method")
//			},
//			GetByEmailFunc: func(email string) (*entities.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(id int) (*entities.User, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByORganizationFunc: func(organization string) ([]entities.User, error) {
//				panic("mock out the GetByORganization method")
//			},
//			ListFunc: func(input *entities.PaginationInput) (*entities.PaginationOutput[*entities.User], error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(user entities.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires repositories.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(user ...entities.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id int) error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(email string) (*entities.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(id int) (*entities.User, error)

	// GetByORganizationFunc mocks the GetByORganization method.
	GetByORganizationFunc func(organization string) ([]entities.User, error)

	// ListFunc mocks the List method.
	ListFunc func(input *entities.PaginationInput) (*entities.PaginationOutput[*entities.User], error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(user entities.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// User is the user argument value.
			User []entities.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID int
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// ID is the id argument value.
			ID int
		}
		// GetByORganization holds details about calls to the GetByORganization method.
		GetByORganization []struct {
			// Organization is the organization argument value.
			Organization string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Input is the input argument value.
			Input *entities.PaginationInput
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// User is the user argument value.
			User entities.User
		}
	}
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockGetByEmail        sync.RWMutex
	lockGetByID           sync.RWMutex
	lockGetByORganization sync.RWMutex
	lockList              sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(user ...entities.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		User []entities.User
	}{
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(user...)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	User []entities.User
} {
	var calls []struct {
		User []entities.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryMock) Delete(id int) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryMock.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepository.DeleteCalls())
func (mock *UserRepositoryMock) DeleteCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepositoryMock) GetByEmail(email string) (*entities.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepositoryMock.GetByEmailFunc: method is nil but UserRepository.GetByEmail was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetByEmailCalls())
func (mock *UserRepositoryMock) GetByEmailCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserRepositoryMock) GetByID(id int) (*entities.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserRepositoryMock.GetByIDFunc: method is nil but UserRepository.GetByID was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserRepository.GetByIDCalls())
func (mock *UserRepositoryMock) GetByIDCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByORganization calls GetByORganizationFunc.
func (mock *UserRepositoryMock) GetByORganization(organization string) ([]entities.User, error) {
	if mock.GetByORganizationFunc == nil {
		panic("UserRepositoryMock.GetByORganizationFunc: method is nil but UserRepository.GetByORganization was just called")
	}
	callInfo := struct {
		Organization string
	}{
		Organization: organization,
	}
	mock.lockGetByORganization.Lock()
	mock.calls.GetByORganization = append(mock.calls.GetByORganization, callInfo)
	mock.lockGetByORganization.Unlock()
	return mock.GetByORganizationFunc(organization)
}

// GetByORganizationCalls gets all the calls that were made to GetByORganization.
// Check the length with:
//
//	len(mockedUserRepository.GetByORganizationCalls())
func (mock *UserRepositoryMock) GetByORganizationCalls() []struct {
	Organization string
} {
	var calls []struct {
		Organization string
	}
	mock.lockGetByORganization.RLock()
	calls = mock.calls.GetByORganization
	mock.lockGetByORganization.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepositoryMock) List(input *entities.PaginationInput) (*entities.PaginationOutput[*entities.User], error) {
	if mock.ListFunc == nil {
		panic("UserRepositoryMock.ListFunc: method is nil but UserRepository.List was just called")
	}
	callInfo := struct {
		Input *entities.PaginationInput
	}{
		Input: input,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(input)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepository.ListCalls())
func (mock *UserRepositoryMock) ListCalls() []struct {
	Input *entities.PaginationInput
} {
	var calls []struct {
		Input *entities.PaginationInput
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(user entities.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		User entities.User
	}{
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	User entities.User
} {
	var calls []struct {
		User entities.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
