CREATE TABLE tenants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_id INT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50) NOT NULL UNIQUE,
    id_card VARCHAR(50) NOT NULL UNIQUE,
    start_date DATETIME NOT NULL,
    end_date DATETIME,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    contract_url VARCHAR(255),
    image_url VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME
);